server:
  port: 8080
  servlet:
    session:
      timeout: 5m
  compression:
    enabled: true
    min-response-size: 2KB


spring:
  devtools:
    restart:
      enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  banner:
    image:
      location: banner.txt

  application:
    name: SpringAdvance
#  config:
#    import: application-web.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/advance?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username : root
    password: 123456

  redis:
    host: localhost
    port: 6379
    password:

  mail:
    host: smtp.163.com
    from: 13203208733@163.com
    username: 13203208733
    password: TJdMK37A9wVh7CBG
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          auth: true
          starttls:
            enable: true
            required: true

servlet:
  tomcat:
    max-swallow-size: -1 # 解决上传图片超过2MB之后，出现连接重置的问题



mybatis-plus:
  configuration:
    #开启下划线转驼峰
    map-underscore-to-camel-case: true
  mapper-locations:


knife4j:
  enable: true
  setting:
    language: zh-CN
  openapi:
    title: SpringAdvance
    description:  一个基于Springboot的后端API测试系统
    version: 1.0.0

#应用通用信息
springdvance:
  jwt:
    issuer: kk_application #签发人
    seceret: KK_Learning #加密密钥
    expire: 432000000 # jwt的有效期，默认30天



security:
  salt: security_salt # 密码加盐, 更安全的做法是每个用户的密码使用独立的盐，并将其保存在用户表中
  salt-index: 3 # 盐插入的位置
