env:
  name: dev

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.36:3306/advance?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username : root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456






  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false # 禁用Thymeleaf模板缓存以支持热部署

